# Generated by Django 5.1 on 2024-09-16 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0002_fieldconfiguration_detail_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelconfiguration',
            name='app',
        ),
        migrations.RemoveField(
            model_name='fieldconfiguration',
            name='model',
        ),
        migrations.RemoveField(
            model_name='fieldconfiguration',
            name='read_permission_groups',
        ),
        migrations.RemoveField(
            model_name='fieldconfiguration',
            name='read_permission_users',
        ),
        migrations.RemoveField(
            model_name='fieldconfiguration',
            name='write_permission_groups',
        ),
        migrations.RemoveField(
            model_name='fieldconfiguration',
            name='write_permission_users',
        ),
        migrations.RemoveField(
            model_name='modelconfiguration',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='modelconfiguration',
            name='read_permission_groups',
        ),
        migrations.RemoveField(
            model_name='modelconfiguration',
            name='read_permission_users',
        ),
        migrations.RemoveField(
            model_name='modelconfiguration',
            name='write_permission_groups',
        ),
        migrations.RemoveField(
            model_name='modelconfiguration',
            name='write_permission_users',
        ),
        migrations.DeleteModel(
            name='AppConfiguration',
        ),
        migrations.DeleteModel(
            name='FieldConfiguration',
        ),
        migrations.DeleteModel(
            name='ModelAction',
        ),
        migrations.DeleteModel(
            name='ModelConfiguration',
        ),
    ]
